name: "Lint"

on:
  pull_request:
  push:

jobs:

  eslint:

    name: "ESLint"
    runs-on: ubuntu-latest

    steps:

       - name: "Checkout the repository"
         uses: actions/checkout@v2

       - name: "Setup Node.js"
         uses: actions/setup-node@v2
         with:
           node-version: 16

       - name: "Install dependences"
         run: |
           npm install

       - name: "Lint with ESLint"
         run: |
           npm run lint
